version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push docker image
          command: |
            export IMAGE_NAME=film-pudding-server
            export TAG=0.1.${CIRCLE_BUILD_NUM}
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
